package com.coolshow.exam.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tm_admin", "id", Admin.class);
		arp.addMapping("tm_admin_roles", "id", AdminRoles.class);
		arp.addMapping("tm_admin_roles_settings", "id", AdminRolesSettings.class);
		arp.addMapping("tm_config", "id", Config.class);
		arp.addMapping("tm_department", "dept_code", Department.class);
		arp.addMapping("tm_exam_detail", "id", ExamDetail.class);
		arp.addMapping("tm_exam_detail_t", "qid", ExamDetailT.class);
		arp.addMapping("tm_exam_info", "id", ExamInfo.class);
		arp.addMapping("tm_log", "id", Log.class);
		arp.addMapping("tm_news", "id", News.class);
		arp.addMapping("tm_news_cate", "id", NewsCate.class);
		arp.addMapping("tm_online", "uid", Online.class);
		arp.addMapping("tm_paper", "id", Paper.class);
		// Composite Primary Key order: pid,qid
		arp.addMapping("tm_paper_detail", "pid,qid", PaperDetail.class);
		arp.addMapping("tm_paper_random", "rid", PaperRandom.class);
		arp.addMapping("tm_paper_section", "id", PaperSection.class);
		// Composite Primary Key order: paperid,usergroupid
		arp.addMapping("tm_paper_usergroup", "paperid,usergroupid", PaperUsergroup.class);
		arp.addMapping("tm_plus", "id", Plus.class);
		arp.addMapping("tm_question", "id", Question.class);
		arp.addMapping("tm_question_collection", "id", QuestionCollection.class);
		arp.addMapping("tm_question_db", "id", QuestionDb.class);
		// Composite Primary Key order: qid,salisa
		arp.addMapping("tm_question_options", "qid,salisa", QuestionOptions.class);
		arp.addMapping("tm_systips", "id", Systips.class);
		arp.addMapping("tm_user", "id", User.class);
		arp.addMapping("tm_user_groups", "id", UserGroups.class);
		arp.addMapping("tm_user_import", "id", UserImport.class);
		// Composite Primary Key order: addtime,usergroupid,userid
		arp.addMapping("tm_user_usergroup", "addtime,usergroupid,userid", UserUsergroup.class);
	}
}

