package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseAdminRolesSettings;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRolesSettings extends BaseAdminRolesSettings<AdminRolesSettings> {
  private static final AdminRolesSettings dao = Singleton.getInstance().getSingletonObject
      (AdminRolesSettings.class);

  /**
   * .
   *
   * @return 获取未关联的所有的权限
   */
  public List findAll() {
    return dao.find(getSql("adminRolesSettings.findAll"));
  }

  /**
   * 获取权限列表
   *
   * @param ptype
   * @return
   */
  public List findByP(Integer ptype) {
    return dao.find(getSql("adminRolesSettings.findByP"), ptype);
  }
}
