package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseAdminRolesSettings;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRolesSettings extends BaseAdminRolesSettings<AdminRolesSettings> {
	public static final AdminRolesSettings dao = new AdminRolesSettings().dao();
	/**
	 * 获取未关联的所有的权限
	 * @return
	 */
	public List getPrivelegesList() {
		String sql = "select * from tm_admin_roles_settings order by porder asc, id asc";
		return dao.find(sql);
	}

	/**
	 * 获取权限列表
	 * @param ptype
	 * @return
	 */
	public List getPrivelegesList(Integer ptype) {
		String sql = "select * from tm_admin_roles_settings where ptype=? order by porder asc, id asc";
		return dao.find(sql, ptype);
	}
}
