package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseConfig;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
    public static final Config dao = Singleton.getInstance().getSingletonObject(Config.class).dao();

    /**
     *.
     * @return 获取所有配置
     */
    public List findAll() {
        return dao.find(getSql("config.findAll"));
    }

    /**
     *.
     * @param id
     * @return 根据id获取配置
     */
    public List findById(Integer id) {
        return dao.find(getSql("config.findById"), id);
    }


    /**
     * 根据key获取配置
     *
     * @param key
     * @return
     */
    public List findByKey(String key) {
        return dao.find(getSql("config"), key);
    }

    /**
     * 添加配置
     *
     * @param confkey
     * @param confval
     * @param remark
     * @param conftype
     * @param vals
     * @return
     */
    public Integer addConfig(String confkey, String confval, String remark, Integer conftype, String vals) {
        String sql = "insert into tm_config(confkey,confval,remark, conftype, vals) values(?,?,?,?,?)";
        return Db.update(sql, confkey, confval, remark, conftype, vals);
    }


    /**
     * 根据key修改配置
     *
     * @param confkey
     * @param confval
     * @return
     */
    public Integer updateConfigByKey(String confval, String confkey) {
        String sql = "update tm_config set confval=? where confkey=?";
        return Db.update(sql, confval, confkey);
    }
}
