package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseConfig;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
    public static final Config dao = Singleton.getInstance().getSingletonObject(Config.class).dao();

    /**
     *.
     * @return 获取所有配置
     */
    public List findAll() {
        return dao.find(getSql("config.findAll"));
    }

    /**
     *.
     * @param id id
     * @return 根据id获取配置
     */
    public List findById(Integer id) {
        return dao.find(getSql("config.findById"), id);
    }


    /**
     *.
     * @param key key
     * @return 返回配置
     */
    public List findByKey(String key) {
        return dao.find(getSql("config.findByKey"), key);
    }

    /**
     *.
     * @param config 配置
     * @return 添加配置
     */
    public Integer add(Config config) {
        return Db.update(getSql("config.add"), config.getConfkey(), config.getConfval(),
            config.getRemark(),config.getId(),config.getCname());
    }


    /**
     *.
     * @param configKey 配置key
     * @param configVal 配置值
     * @return 根据key修改配置
     */
    public Integer updateByConfigKey(String configVal, String configKey) {
        return Db.update(getSql("config.updateByConfigKey"), configVal, configKey);
    }
}
