package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseConfig;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
    public static final Config dao = new Config().dao();

    /**
     * 获取所有配置
     *
     * @return
     */
    public List getConfigs() {
        String sql = "select * from tm_config";
        return dao.find(sql);
    }

    /**
     * 根据id获取配置
     *
     * @param id
     * @return
     */
    public List getConfigById(Integer id) {
        String sql = "select * from tm_config where id = ?";
        return dao.find(sql, id);
    }


    /**
     * 根据key获取配置
     *
     * @param key
     * @return
     */
    public List getConfigByKey(String key) {
        String sql = "select * from tm_config where confkey = ?";
        return dao.find(sql, key);
    }

    /**
     * 添加配置
     *
     * @param confkey
     * @param confval
     * @param remark
     * @param conftype
     * @param vals
     * @return
     */
    public Integer addConfig(String confkey, String confval, String remark, Integer conftype, String vals) {
        String sql = "insert into tm_config(confkey,confval,remark, conftype, vals) values(?,?,?,?,?)";
        return Db.update(sql, confkey, confval, remark, conftype, vals);
    }


    /**
     * 根据key修改配置
     *
     * @param confkey
     * @param confval
     * @return
     */
    public Integer updateConfigByKey(String confval, String confkey) {
        String sql = "update tm_config set confval=? where confkey=?";
        return Db.update(sql, confval, confkey);
    }
}
