package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseDepartment;
import com.jfinal.plugin.activerecord.Db;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
  public static final Department dao = Singleton.getInstance().getSingletonObject(Department.class).dao();

  /**
   * 获取全部部门
   *
   * @return
   */
  public List findAll() {
    return dao.find(getSql("department.findAll"));
  }

  /**
   * 根据部门编码获取部门
   *
   * @param deptCode
   * @return
   */
  public List findByDeptCode(String deptCode) {

    return (List)super.findById(deptCode);
  }

  /**
   * 获取全部部门名字,部门编码
   *
   * @return
   */
  public List findDeptNameAndCode() {
    return dao.find(getSql("department.findDeptNameAndCode"));
  }

  /**
   * .
   *
   * @param orgDc 组织
   * @return 通过组织修改部门
   */
//  public Integer updateDeptByOrgDc(OrgDc orgDc) {
//    String sql = "update tm_department set dept_name = ? , parent_dept_code = ?,status = ?,create_date = ?,modify_date = ? where dept_code = ?";
//    return Db.update(sql, orgDc.getOrgName(), orgDc.getParentOrgCode(), orgDc.getIsEnable(),
//        orgDc.getCreateTime(), orgDc.getUpdateTime(), orgDc.getOrgCode());
//  }

  /**
   * @param orgDc 组织
   * @return 添加部门
   */
//  public Integer addDeptByOrg(OrgDc orgDc) {
//    String sql = "insert into tm_department (dept_code ,dept_name ,parent_dept_code ,status ," +
//        "create_date ,modify_date) values (?,?,?,?,?,?)";
//    return Db.update(sql, orgDc.getOrgCode(), orgDc.getOrgName(), orgDc.getParentOrgCode(),
//        orgDc.getIsEnable(), orgDc.getCreateTime(), orgDc.getUpdateTime());
//  }
}
