package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseExamDetailT;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamDetailT extends BaseExamDetailT<ExamDetailT> {
	public static final ExamDetailT dao = new ExamDetailT().dao();
}
