package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseExamDetailT;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamDetailT extends BaseExamDetailT<ExamDetailT> {
	private static final ExamDetailT dao = Singleton.getInstance().getSingletonObject
			(ExamDetailT.class).dao();
}
