package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseExamDetail;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamDetail extends BaseExamDetail<ExamDetail> {
    public static final ExamDetail dao = new ExamDetail().dao();

    /**
     * 考试详情
     *
     * @param pid
     * @return
     */
    public List examDetail(Integer pid) {
        String sql = "select t.*,(t.mnum/t.totalnum)*100 tpercent from (  select td.qid,count(1) totalnum,  sum(if(td.score<=0,0,1)) mnum  from tm_exam_detail td where td.pid=? group by td.qid) t";
        return dao.find(sql, pid);
    }


}
