package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseLog;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
    public static final Log dao = new Log().dao();

    /**
     * 添加日志
     * @param logtype
     * @param usertype
     * @param username
     * @param uid
     * @param ip
     * @param remark
     * @return
     */

    public Integer addLog(String logtype, String usertype, String username, String uid, String ip, String remark) {
        String sql = "insert into tm_log(logtype,usertype,username,uid,logtime,ip,remark) values(?,?,?,?," +
                11111 + ",?,?)";
        return Db.update(sql, logtype, usertype, username, uid, ip, remark);
    }
}
