package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseNewsCate;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsCate extends BaseNewsCate<NewsCate> {
  private static final NewsCate dao = Singleton.getInstance().getSingletonObject(NewsCate.class)
      .dao();

  /**
   * .
   *
   * @param id id
   * @return 根据id获取新闻类别
   */
  public List findById(Integer id) {
    return dao.find(getSql("newsCate.findById"), id);
  }

  /**
   * .
   *
   * @param parentid
   * @return
   */
  public List findByParentId(Integer parentid) {
    return dao.find(getSql("newsCate.findByParentId"), parentid);
  }

  /**
   * .
   *
   * @return 获取全部新闻类别
   */
  public List findAll() {
    return dao.find(getSql("newsCate.findAll"));
  }

  /**
   * .
   *
   * @param newsCate 新闻类别
   * @return 添加
   */
  public Integer add(NewsCate newsCate) {
    return Db.update(getSql("newsCate.add"), newsCate.getCname(), newsCate.getParentid(),
        newsCate.getAdminid(), newsCate.getOrderid(), newsCate.getRemark());
  }

  /**
   * .
   *
   * @param newsCate 新闻类别
   * @return 修改新闻类别
   */
  public Integer update(NewsCate newsCate) {
    return Db.update(getSql("newsCate.update"), newsCate.getCname(), newsCate.getParentid(),
        newsCate.getAdminid(), newsCate.getOrderid(), newsCate.getRemark(), newsCate.getId());
  }


  /**
   *.
   * @param id id
   * @return 根据id删除新闻类别
   */
  public Integer delete(Integer id) {
    return Db.update(getSql("newsCate.delete"), id);
  }


}
