package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseNews;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
    public static final News dao = new News().dao();

    /**
     * 根据id获取新闻
     *
     * @param id
     * @return
     */
    public List getNewsById(Integer id) {
        String sql = "select * from tm_news where id = ?";
        return dao.find(sql, id);
    }

    /**
     * 获取新闻
     *
     * @param rows
     * @return
     */
    public List getNewsList(Integer rows) {
        String sql = "select title,id,DATE_FORMAT(postdate,'%Y-%m-%d %h:%i %p') pdate from tm_news order by id desc limit 0,?";
        return dao.find(sql, rows);
    }

    /**
     * 获取新闻
     *
     * @param rows
     * @param classid
     * @return
     */
    public List getNewsList(Integer rows, String classid) {
        String sql = "select title,id,DATE_FORMAT(postdate,'%Y-%m-%d %h:%i %p') pdate from tm_news where classid=" +
                classid + " order by id desc limit 0,?";
        return dao.find(sql, rows);
    }

    /**
     * 获取新闻
     * @param rows
     * @param classids
     * @return
     */
    public List getNewsList(Integer rows, String[] classids) {

        String sql = "select title,id,DATE_FORMAT(postdate,'%Y-%m-%d %h:%i %p') pdate from tm_news where classid in (?) order by id desc limit 0,?";
        return dao.find(sql, rows,classids);
    }

    /**
     * 添加新闻
     *
     * @param title
     * @param title_color
     * @param classid
     * @param content
     * @param status
     * @param summary
     * @param totop
     * @param visit
     * @param photo
     * @param author
     * @param outlink
     * @param newsfrom
     * @param adminid
     * @return
     */
    public Integer addNews(String title, String title_color, Integer classid, String content, String status, String summary,
                           Integer totop, Integer visit, String photo, String author, String outlink, String newsfrom, Integer adminid) {
        String sql = "insert into tm_news(title,title_color,classid,content,status,summary,totop,visit,postdate,photo,author,outlink,newsfrom,adminid)  values(?,?,?,?,?,?,?,?," +
                11111 + ",?,?,?,?,?)";
        return Db.update(sql, title, title_color, classid, content, status, summary, totop, visit, photo, author,
                outlink, newsfrom, adminid);
    }

    /**
     * 添加观看新闻记录
     *
     * @param id
     * @return
     */
    public Integer addNewsVisit(Integer id) {
        String sql = "update tm_news set visit=(visit+1) where id=?";
        return Db.update(sql, id);
    }

    /**
     * 修改新闻
     *
     * @param id
     * @param title
     * @param title_color
     * @param classid
     * @param content
     * @param status
     * @param summary
     * @param totop
     * @param visit
     * @param photo
     * @param author
     * @param outlink
     * @param newsfrom
     * @param adminid
     * @return
     */
    public Integer updateNews(Integer id, String title, String title_color, Integer classid, String content, String status, String summary,
                              Integer totop, Integer visit, String photo, String author, String outlink, String newsfrom, Integer adminid) {
        String sql = "update tm_news set title=?,title_color=?,classid=?,content=?,status=?,summary=?,totop=?,visit=?,photo=?,author=?,outlink=?,newsfrom=?,adminid=? where id=?";

        return Db.update(sql, title, title_color, classid, content, status, summary, totop, visit, photo, author, outlink,
                newsfrom, adminid, id);
    }


    /**
     * 根据id删除新闻
     *
     * @param id
     * @return
     */
    public Integer deleteNewsById(Integer id) {
        String sql = "delete from tm_news where id = ?";
        return Db.update(sql, id);
    }


}
