package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseOnline;
import com.jfinal.plugin.activerecord.Db;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Online extends BaseOnline<Online> {
  private static final Online dao = Singleton.getInstance().getSingletonObject(Online.class);


  /**
   * .
   *
   * @param uid 用户id
   * @return 获取在线状态
   */
  public List findById(Integer uid) {
    return dao.find(getSql("online.findById"), uid);
  }


  /**
   * .
   *
   * @param minute 间隔时间
   * @return 获取试卷在线答题人数
   */
  //todo 系统更新时间
  public List onlineNum(Date datetime, Integer minute) {
    return dao.find(getSql("online.onlineNum"), datetime, minute);
  }

  /**
   * .
   *
   * @param pid    试卷id
   * @param minute 间隔时间
   * @return 在线的用户
   */
  //todo 系统时间
  public List onlineUsers(Integer pid, Date datetime, Integer minute) {
    return dao.find(getSql("online.onlineUsers"), pid, datetime, minute);
  }

  /**
   * .
   *
   * @param scmd
   * @param uid
   * @return 发送命令
   */
  public Integer sendCommand(String scmd, Integer uid) {
    return Db.update(getSql("online.sendCommand"), scmd, uid);
  }

  /**
   * .
   *
   * @param pid 试卷id
   * @param uid 用户id
   * @return 添加在线状态
   */
  //todo 系统时间
  public Integer updateLastTime(Date datetime, Integer pid, Integer uid) {
    return Db.update(getSql("online.updateLastTime"), datetime, pid, uid);
  }

  /**
   * .
   *
   * @param uid 用户id
   * @return 下线
   */

  public int delete(Integer uid) {
    return Db.update(getSql("online.delete"), uid);
  }

  /**
   * .
   *
   * @param online online
   * @return 插入在线状态
   */
  //todo 系统时间
  public Integer add(Online online) {
    return Db.update(getSql("online.add"), online.getUid(), online.getPid(), online.getLasttime(),
        online.getExta(), online.getIp());
  }

}
