package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BasePaper;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Paper extends BasePaper<Paper> {
  public static final Paper dao = new Paper().dao();

  /**
   * .
   *
   * @param paper 试卷
   * @return 添加试卷
   */
  public Integer addPaper(Paper paper) {
    StringBuilder sb = new StringBuilder();
    sb.append("insert into tm_paper(paper_name,adminid,departmentid,status,starttime,endtime")
        .append("paper_minute,total_score,remark,qorder,postdate,show_score, isranpaper)")
        .append(" values(?,?,?,?,?,?,?,?,?,?," + 11111 + ",?,?)");
    return Db.update(sb.toString(), paper.getPaperName(), paper.getAdminid(),
        paper.getDepartmentid(), paper.getStatus(), paper.getStarttime(), paper.getEndtime(),
        paper.getPaperMinute(), paper.getTotalScore(), paper.getRemark(), paper.getQorder(),
        paper.getShowScore(), paper.getIsranpaper());
  }

  /**
   * .
   *
   * @param paper 试卷
   * @return 添加试卷和答案
   */
  public Integer addPaperAndResultGenKey(Paper paper) {
    StringBuilder sb = new StringBuilder();
    sb.append("insert into tm_paper(paper_name,adminid,departmentid,status,starttime,endtime,")
        .append("paper_minute,total_score,remark,qorder,postdate,show_score, isranpaper)  ").append(
        "values(?,?,?,?,?,?,?,?,?,?," + 111111 + ",?,?)");
    return Db.update(sb.toString(), paper.getPaperName(), paper.getAdminid(),
        paper.getDepartmentid(), paper.getStatus(), paper.getStarttime(), paper.getEndtime(),
        paper.getPaperMinute(), paper.getTotalScore(), paper.getRemark(), paper.getQorder(),
        paper.getShowScore(), paper.getIsranpaper());
  }

  /**
   * .
   *
   * @param id
   * @return
   * @throws Exception
   */
  public List getPaperById(Integer id) {
    String sql = "select * from tm_paper where id=?";
    return dao.find(sql, id);
  }

  /**
   * .
   *
   * @param paper
   * @return 修改试卷
   */
  public Integer updatePaper(Paper paper) {
    StringBuilder sb = new StringBuilder();
    sb.append("update tm_paper set paper_name=?,status=?,starttime=?,endtime=?,paper_minute=?,").
        append("remark =?,qorder =?,show_score =?,isranpaper =?where id =?");
    return Db.update(sb.toString(), paper.getPaperName(), paper.getStatus(), paper.getStarttime(),
        paper.getEndtime(), paper.getPaperMinute(), paper.getRemark(), paper.getQorder(),
        paper.getShowScore(), paper.getIsranpaper(), paper.getId());
  }

  /**
   * .
   *
   * @param id 删除试卷id
   * @return 删除试卷
   */
  public Integer deletePaper(Integer id) {
    String sql = "delete from tm_paper where id = ?";
    return Db.update(sql, id);
  }

  /**
   * .
   *
   * @param id 删除试卷id
   * @return 逻辑删除试卷
   */
  public Integer LoginDeletePaper(Integer id) {
    String sql = "update tm_paper set status='9' where id = ?";
    return Db.update(sql, id);
  }

  /**
   * .
   * @param pid
   * @param totalscore 试卷总分
   * @return
   */
  public Integer updatePaperTotalScore(Integer pid, Integer totalscore) {
    String sql = "update tm_paper set total_score=? where id=?";
    return Db.update(sql, totalscore, pid);
  }
}
