package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BasePaperRandom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaperRandom extends BasePaperRandom<PaperRandom> {
	public static final PaperRandom dao = new PaperRandom().dao();
}
