package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BasePaperSection;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaperSection extends BasePaperSection<PaperSection> {
	public static final PaperSection dao = new PaperSection().dao();

    /**
     * 添加试卷选项
     *
     * @param pid
     * @param section_name
     * @param remark
     * @param per_score
     * @param quesnums
     * @param queslevel
     * @param quesdbid
     * @param questype
     * @return
     */
    public Integer addPaperSection(Integer pid, String section_name, String remark, Integer per_score, Integer quesnums, Integer queslevel,
                                   Integer quesdbid, Integer questype) {
        String sql = "insert into tm_paper_section(pid,section_name,remark,per_score,quesnums,queslevel,quesdbid,questype) values(?,?,?,?,?,?,?,?)";
        return Db.update(sql, pid, section_name, remark, per_score, quesnums, queslevel, quesdbid, questype);
    }


    /**
     * 根据id获取试卷选项
     *
     * @param id
     * @return
     */
    public List getPaperSectionById(Integer id) {
        String sql = "select * from tm_paper_section where id=?";
        return dao.find(sql, id);
    }

    /**
     * 修改试卷选项
     * @param sid
     * @param section_name
     * @param remark
     * @param per_score
     * @param quesnums
     * @param queslevel
     * @param quesdbid
     * @param questype
     * @return
     */
    public int updatePaperSection(Integer sid, String section_name, String remark, Integer per_score, Integer quesnums,
                                  Integer queslevel, Integer quesdbid, Integer questype) {
        String sql = "update tm_paper_section set section_name=?,remark=?,per_score=?,quesnums=?,queslevel=?,quesdbid=?,questype=? where id=?";
        return Db.update(sql, section_name, remark, per_score, quesnums, queslevel, quesdbid, questype, sid);
    }


    /**
     * 删除试卷选项
     * @param id
     * @return
     */
    public Integer deletePaperSection(Integer id) {
        String sql = "delete from tm_paper_section where id = ?";
        return Db.update(sql, id);
    }


    /**
     * 修改试卷总分
     * @param pid
     * @return
     */
    public Integer updateTotalScore(Integer pid) {
        String sql = "update tm_paper set total_score=(select sum(per_score*quesnums) tts from tm_paper_section where pid=?) where id=?";
        return Db.update(sql, pid, pid);
    }

    /**
     * 修改试卷总分根据详情
     * @param pid
     * @return
     */
    public Integer updateTotalScoreByPaperDetail(Integer pid) {
        String sql = "update tm_paper set total_score=(select sum(score) from tm_paper_detail where pid=?) where id=?";
        return Db.update(sql,pid,pid);
    }


    /**
     * 删除试卷选项根据pid
     * @param pid
     * @return
     */
    public Integer deletePaperSectionByPid(Integer pid) {
        String sql = "delete from tm_paper_section where pid = ?";
        return Db.update(sql, pid);
    }

    /**
     * 获取试卷选项
     * @param pid
     * @return
     */
    public List getPaperSectionList(Integer pid) {
        String sql = "select * from tm_paper_section where pid=? order by id asc";
        return dao.find(sql, pid);
    }
}
