package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BasePlus;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plus extends BasePlus<Plus> {
  private static final Plus dao = Singleton.getInstance().getSingletonObject(Plus.class).dao();

  public Integer add(Plus plus) {
    return Db.update(getSql("plus.add"), plus.getPname(), plus.getPdesc(), plus.getPhoto(),
        plus.getVurl(), plus.getStatus(), plus.getPurl());
  }

  public Integer update(Plus plus) {
    return Db.update(getSql("plus.update"), plus.getPname(), plus.getPdesc(), plus.getPhoto(),
        plus.getVurl(), plus.getStatus(), plus.getPurl(), plus.getId());
  }

  public List findById(Integer id) {
    return dao.find(getSql("plus.findById"), id);
  }

  public Integer delete(Integer id) {
    return Db.update(getSql("plus.delete"), id);
  }
}
