package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BasePlus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plus extends BasePlus<Plus> {
	public static final Plus dao = new Plus().dao();
}
