package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseQuestionOptions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionOptions extends BaseQuestionOptions<QuestionOptions> {
	public static final QuestionOptions dao = new QuestionOptions().dao();
}
