package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseQuestionCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionCollection extends BaseQuestionCollection<QuestionCollection> {
	public static final QuestionCollection dao = new QuestionCollection().dao();
}
