package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseQuestionCollection;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionCollection extends BaseQuestionCollection<QuestionCollection> {
	public static final QuestionCollection dao = new QuestionCollection().dao();

	public int add(int qid, int uid, int did)
	{

		return execute(sql, qid, uid, did );
	}

	public
	public int deleteQc(int id)
			throws Exception
	{
		String sql = "delete from tm_question_collection where id=?";
		return execute(sql, id );
	}

	public List<Map> getAllQcByUID(String uid)
	{
		String sql = "select tq.* from tm_question_collection tc left join tm_question tq on tc.qid = tq.id where tc.uid = ? order by tc.id desc";
		try
		{
			return query(sql, new Object[] { uid });
		} catch (Exception e) {
			e.printStackTrace();
		}return null;
	}
}
