package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseSystips;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Systips extends BaseSystips<Systips> {
	public static final Systips dao = new Systips().dao();
}
