package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseUserGroups;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGroups extends BaseUserGroups<UserGroups> {
	public static final UserGroups dao = new UserGroups().dao();

	/**
	 * 根据部门ID获取部门
	 * @param groupId
	 * @return
	 */
	public List getGroup(Integer groupId) {

		String sql = "select * from tm_user_groups where id = ?";
		return dao.find(sql, groupId);
	}

    /**
     *获取全部集团
     * @return
     */
	public List getGroup(){
		String sql = "select * from tm_user_groups";
		return dao.find(sql);

	}

    /**
     * 获取全部集团名字和编码
     * @return
     */
	public List getGroupNameAndCode(){
		String sql = "select id,groupname from tm_user_groups order by id desc";
		return dao.find(sql);
	}

}
