package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

//	public int addUser(String userno, String dept_code, String username, String userpass, String photo, String status,
//										 String realname, String email, String mobi, String remark, int gid) throws Exception {
//		String sql = "insert into tm_user(userno,dept_code,username,userpass,photo,status,regdate,realname,email,mobi,remark,gid,logintimes) values(?,?,?,?,?,?,"
//				+ SystemCode.SYSDATE + ",?,?,?,?,?,0)";
//		return execute(sql, userno, dept_code, username, userpass, photo, status, realname, email, mobi, remark, gid);
//	}
//
//	public List<Map<String, String>> getUserListByDept_code(String dept_code) throws Exception {
//		String sql = "select * from tm_user where dept_code = " + dept_code + " ";
//		return query(sql);
//	}
//
//	public List<Map<String, String>> getUserListByDept_codeNotInAdmin(String dept_code) throws Exception {
//		String sql = "select * from tm_user where dept_code = " + dept_code
//				+ " and username not in (select username from tm_admin)";
//		return query(sql);
//	}
//
//	/*
//	 * oa数据同步-添加新用户
//	 */
//	public int addUserFromEsb(String userno, String dept_code, String username, String userpass, String realname,
//														String email, String mobi, Date updateTime) throws Exception {
//		String sql = "insert into tm_user"
//				+ "(userno,dept_code,username,userpass,status,regdate,realname,email,mobi,logintimes,lastModifyTime) "
//				+ "values" + "(?,?,?,?,1," + SystemCode.SYSDATE + ",?,?,?,0,?)";
//		return execute(sql, userno, dept_code, username, userpass, realname, email, mobi, updateTime);
//	}
//
//	public Map getUserByUserName(String username) throws Exception {
//		String sql = "select * from tm_user where username = ? and status = ?";
//		return uniqueQuery(sql,  username, "1" );
//	}
//
//	public Map getUserById(int id) throws Exception {
//		String sql = "select tu.*,tg.groupname from tm_user tu left join tm_user_groups tg on tg.id=tu.gid where tu.id = ?";
//		return uniqueQuery(sql, id);
//	}
//
//	public Map getUserByUserNo(String userno) throws Exception {
//		String sql = "select * from tm_user where userno = ?";
//		return uniqueQuery(sql, new Object[] { userno });
//	}
//
//	public Map getUserByUserNameAndUserPass(String username, String userpass) throws Exception {
//		String sql = "select * from tm_user where username = ? and userpass = ?";
//		return uniqueQuery(sql, new Object[] { username, userpass });
//	}
//
//	public int updateUser(int id, String userno, String userpass, String photo, String status, String realname,
//												String email, String mobi, String remark, int gid) throws Exception {
//		String sql = "update tm_user set userno=?,userpass=?,photo=?,status=?,realname=?,email=?,mobi=?,remark=?,gid=? where id=?";
//		return execute(sql, userno, userpass, photo, status, realname, email, mobi, remark, gid, id);
//	}
//
//	public int updateUser(int id, String userno, String photo, String status, String realname, String email,
//												String mobi, String remark, int gid) throws Exception {
//		String sql = "update tm_user set userno=?,photo=?,status=?,realname=?,email=?,mobi=?,remark=?,gid=? where id=?";
//		return execute(sql, userno, photo, status, realname, email, mobi, remark, gid, id);
//	}
//
//	// 删除用户时也将该用户从用户分组里面移除
//	public int deleteUserById(int id) throws Exception {
//		int flag = 0;
//		String sql = "delete from tm_user where id = ?";
//		flag = execute(sql, id);
//
//		List userList = getUserGroupIds(id);
//		String[] ids;
//		if (userList != null && userList.size() > 0) {
//			ids = new String[userList.size()];
//			int length = userList.size();
//			for (int i = 0; i < length; i++) {
//				ids[i] = (String) userList.get(i);
//			}
//			flag = batchDeleteUserGroup(ids);
//		} else {
//			return flag;
//		}
//
//		return flag;
//
//	}
//
//	public int updateLastLogin(int id) throws Exception {
//		String sql = "update tm_user set lastlogin = " + SystemCode.SYSDATE + ",logintimes=(logintimes+1) where id = ?";
//		return execute(sql, id);
//	}
//
//	public int getTotalUsers() {
//		String sql = "select count(1) TOTALUSERS from tm_user";
//		try {
//			Map map = uniqueQuery(sql, new Object[0]);
//			String s_total_users = String.valueOf(map.get("TOTALUSERS"));
//			return Integer.parseInt(s_total_users);
//		} catch (Exception e1) {
//			e1.printStackTrace();
//		}
//		return -1;
//	}
//
//	/*
//	 * oa数据同步-判断用户是否存在
//	 */
//	public boolean exitUser(String username) {
//		String sql = "select * from tm_user where userno = ?";
//		try {
//			Map map = uniqueQuery(sql, new Object[] { username });
//			if (map != null && map.size() > 0)
//				return true;
//		} catch (Exception e1) {
//			e1.printStackTrace();
//		}
//		return false;
//	}
//
//	/*
//	 * oa数据同步-根据离职标识删除离职用户
//	 */
//	public int deleteUserByStaffNo(String staffNo) throws Exception {
//		String sql = "update tm_user set status=0 where userno = ?";
//		return execute(sql, new Object[] { staffNo });
//	}
//
//	/*
//	 * oa数据同步-更新用户
//	 */
//	public int updateUserFromEsb(String realname, Integer isEnable, Date lastModifyTime, String dept_code,
//															 String staffNo, String email, String mobi) throws Exception {
//		int status = (isEnable == 0 ? 0 : 1);
//		String sql = "update tm_user set realname = ?, status=" + status
//				+ ",lastmodifyTime = ?,dept_code = ? , email=?,mobi=? where userno=?";
//		return execute(sql, realname, lastModifyTime, dept_code, email, mobi, staffNo);
//	}
//
//	// 批量删除用户
//	public int batchDelete(String[] ids) throws Exception {
//		List list = new ArrayList();
//		if (ids != null) {
//			String[] arrayOfString;
//			int j = (arrayOfString = ids).length;
//			for (int i = 0; i < j; i++) {
//				String s = arrayOfString[i];
//				list.add(new Object[] { s });
//			}
//		}
//		return batchExcute("delete from tm_user where id=?", list);
//	}
//
//	// 批量删除用户所属组
//	public int batchDeleteUserGroup(String[] ids) throws Exception {
//		List list = new ArrayList();
//		if (ids != null) {
//			String[] arrayOfString;
//			int j = (arrayOfString = ids).length;
//			for (int i = 0; i < j; i++) {
//				String s = arrayOfString[i];
//				list.add(new Object[] { s });
//			}
//		}
//		return batchExcute("delete from tm_user_usergroup where userid=?", list);
//	}
//
//	// 批量审核
//	public int batchSetStatus(String[] ids, String status) throws Exception {
//		List list = new ArrayList();
//		if (ids != null) {
//			String[] arrayOfString;
//			int j = (arrayOfString = ids).length;
//			for (int i = 0; i < j; i++) {
//				String s = arrayOfString[i];
//				list.add(new Object[] { status, s });
//			}
//		}
//		return batchExcute("update tm_user set status=? where id=?", list);
//	}
//
//	// 批量移动到用户群组
//	public int batchSetGid(String[] ids, int gid) throws Exception {
//		List list = new ArrayList();
//		if (ids != null) {
//			String[] arrayOfString;
//			int j = (arrayOfString = ids).length;
//			for (int i = 0; i < j; i++) {
//				String s = arrayOfString[i];
//				list.add(new Object[] { Integer.valueOf(gid), s });
//			}
//		}
//		return batchExcute("update tm_user set gid=? where id=?", list);
//	}
//
//	// 批量移动到新用户群组
//	public int batchSetUserGroup(String[] ids, int gid) throws Exception {
//		List list = new ArrayList();
//		batchDeleteUserGroup(ids);
//		if (ids != null) {
//			String[] arrayOfString;
//			int j = (arrayOfString = ids).length;
//			for (int i = 0; i < j; i++) {
//				String s = arrayOfString[i];
//				list.add(new Object[] { Integer.valueOf(gid), s });
//			}
//		}
//		return batchExcute("insert into tm_user_usergroup(usergroupid,userid) values(?,?)", list);
//	}
//
//	public void setUserGroups(int uid, String[] gids) throws Exception {
//		String sql = "delete from tm_user_usergroup where userid=?";
//		execute(sql, uid);
//
//		if ((gids != null) && (gids.length > 0)) {
//			String[] arrayOfString;
//			int j = (arrayOfString = gids).length;
//			for (int i = 0; i < j; i++) {
//				String gid = arrayOfString[i];
//				sql = "insert into tm_user_usergroup(userid,usergroupid) values(?,?)";
//				execute(sql, uid, UserDao.StringToInt(gid));
//			}
//		} /*
//			 * else{ sql =
//			 * "insert into tm_user_usergroup(userid,usergroupid) values(?,0)";
//			 * execute(sql, new Object[] { uid)}); }
//			 */
//		DBUtil.commit();
//	}
//
//	public static synchronized int StringToInt(String source) {
//		try {
//			return Integer.parseInt(source);
//		} catch (NumberFormatException e) {
//		}
//		return 55537;
//	}
//
//	public List getUserGroupIds(int userid) throws Exception {
//		String sql = "select usergroupid from tm_user_usergroup where userid=?";
//		return query(sql, userid);
//	}
//
//	public List getGroupNamesByIds(List groupIdSList) throws Exception {
//		List groupNamelist = new ArrayList();
//		Map nameMap;
//		if (groupIdSList != null && groupIdSList.size() > 0) {
//			int length = groupIdSList.size();
//			for (int i = 0; i < length; i++) {
//				int groupid = (Integer) groupIdSList.get(i);
//				String sql = "select groupname from tm_user_groups where id=?";
//				nameMap = uniqueQuery(sql, groupid);
//				groupNamelist.add(nameMap.get("GROUPNAME"));
//			}
//		}
//
//		return groupNamelist;
//
//	}
//
//	// 将用户从用户分组里面移除
//	public int removeFromGroup(int userid, int usergroupid) throws Exception {
//
//		String sql = "delete from tm_user_usergroup where userid = ? and usergroupid = ?";
//		return execute(sql, userid, usergroupid);
//
//	}
//
//	// 将用户添加进用户分组
//	public int AddUserToGroup(String username, String groupid) throws Exception {
//		int flag = 1;
//		int userid;
//
//		Map map = getUserByUserName(username);
//		if (map == null) {
//			flag = -1;// 没有该用户
//			return flag;
//		} else {
//			userid = Integer.parseInt(String.valueOf(map.get("ID")));
//		}
//
//		Map map2 = getUsergroup(userid, Integer.parseInt(groupid));
//		if (map2 != null) {
//			flag = 2;// 该用户已经在该分组里面了
//			return flag;
//		} else {
//			String sql = "insert into tm_user_usergroup values (?,?,?)";
//			execute(sql, userid, groupid, new Date());
//		}
//		return flag;
//	}
//
//	// 通过用户分组组名得到编号
//	public Map getGroupByName(String groupname) throws Exception {
//
//		String sql = "select id from tm_user_groups where groupname=? ";
//		return uniqueQuery(sql, new Object[] { groupname });
//
//	}
//
//	public Map getUsergroup(int userid, int usergroupid) throws Exception {
//		String sql = "select * from tm_user_usergroup where userid = ? and usergroupid=? ";
//		return uniqueQuery(sql, userid, usergroupid);
//
//	}
}
