package com.coolshow.exam.model;

import com.coolshow.exam.model.base.BaseUserUsergroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserUsergroup extends BaseUserUsergroup<UserUsergroup> {
	public static final UserUsergroup dao = new UserUsergroup().dao();
}
