package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseUserImport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserImport extends BaseUserImport<UserImport> {
  public static final UserImport dao = Singleton.getInstance().getSingletonObject(UserImport.class)
      .dao();
}
