package com.coolshow.exam.model;

import com.coolshow.exam.common.Singleton;
import com.coolshow.exam.model.base.BaseUserGroups;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGroups extends BaseUserGroups<UserGroups> {
  private static final UserGroups dao = Singleton.getInstance().getSingletonObject(UserGroups.class);

  /**
   * .
   *
   * @param groupId 集团id
   * @return 根据部门ID获取部门
   */
  public List findById(Integer groupId) {

    return dao.find(getSql("userGroups.findById"), groupId);
  }

  /**
   * 获取全部集团
   *
   * @return
   */
  public List findAll() {
    return dao.find(getSql("userGroups.findAll"));

  }

  /**
   * .
   *
   * @return 查找集团名字和id
   */
  public List findIdAndName() {
    return dao.find(getSql("userGroups.findIdAndName"));
  }

}
