#namespace("admin")
  #include("admin.sql")
#end
#namespace("adminRoles")
  #include("adminRoles.sql")
#end
#namespace("adminRolesSettings")
  #include("adminRolesSettings.sql")
#end
#namespace("config")
  #include("config.sql")
#end
#namespace("department")
  #include("department.sql")
#end
#namespace("examDetail")
  #include("examDetail.sql")
#end
#namespace("examDetailT")
  #include("examDetailT.sql")
#end
#namespace("examInfo")
  #include("examInfo.sql")
#end
#namespace("log")
  #include("log.sql")
#end
#namespace("news")
  #include("news.sql")
#end
#namespace("newsCate")
  #include("newsCate.sql")
#end
#namespace("online")
  #include("online.sql")
#end
#namespace("paper")
  #include("paper.sql")
#end
#namespace("paperDetail")
  #include("paperDetail.sql")
#end
#namespace("paperRandom")
  #include("paperRandom.sql")
#end
#namespace("paperSection")
  #include("paperSection.sql")
#end
#namespace("paperUserGroup")
  #include("paperUserGroup.sql")
#end
#namespace("plus")
  #include("plus.sql")
#end
#namespace("question")
  #include("question.sql")
#end
#namespace("questionCollection")
  #include("questionCollection.sql")
#end
#namespace("questionDd")
  #include("questionDd.sql")
#end
#namespace("questionOptions")
  #include("questionOptions.sql")
#end
#namespace("sysTips")
  #include("sysTips.sql")
#end
#namespace("user")
  #include("user.sql")
#end
#namespace("userGroups")
  #include("userGroups.sql")
#end
#namespace("userImport")
  #include("userImport.sql")
#end
#namespace("userUserGroup")
  #include("userUserGroup.sql")
#end


