#namespace("admin")
  #include("admin.sql")
#end
#namespace("adminRoles")
  #include("adminRoles.sql")
#end
#namespace("adminRolesSettings")
  #include("adminRolesSettings.sql")
#end
#namespace("config")
  #include("config.sql")
#end
#namespace("department")
  #include("department.sql")
#end
#namespace("examDetail")
  #include("examDetail.sql")
#end