package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserUsergroup<M extends BaseUserUsergroup<M>> extends Model<M> implements IBean {

	public M setUserid(Integer userid) {
		set("userid", userid);
		return (M)this;
	}

	public Integer getUserid() {
		return get("userid");
	}

	public M setUsergroupid(Integer usergroupid) {
		set("usergroupid", usergroupid);
		return (M)this;
	}

	public Integer getUsergroupid() {
		return get("usergroupid");
	}

	public M setAddtime(java.util.Date addtime) {
		set("addtime", addtime);
		return (M)this;
	}

	public java.util.Date getAddtime() {
		return get("addtime");
	}

}
