package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public M setDeptCode(String deptCode) {
		set("dept_code", deptCode);
		return (M)this;
	}

	public String getDeptCode() {
		return get("dept_code");
	}

	public M setDeptName(String deptName) {
		set("dept_name", deptName);
		return (M)this;
	}

	public String getDeptName() {
		return get("dept_name");
	}

	public M setParentDeptCode(String parentDeptCode) {
		set("parent_dept_code", parentDeptCode);
		return (M)this;
	}

	public String getParentDeptCode() {
		return get("parent_dept_code");
	}

	public M setDeptDesc(String deptDesc) {
		set("dept_desc", deptDesc);
		return (M)this;
	}

	public String getDeptDesc() {
		return get("dept_desc");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return get("status");
	}

	public M setCreator(String creator) {
		set("creator", creator);
		return (M)this;
	}

	public String getCreator() {
		return get("creator");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setModifier(String modifier) {
		set("modifier", modifier);
		return (M)this;
	}

	public String getModifier() {
		return get("modifier");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
		return (M)this;
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
