package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOnline<M extends BaseOnline<M>> extends Model<M> implements IBean {

	public M setUid(Integer uid) {
		set("uid", uid);
		return (M)this;
	}

	public Integer getUid() {
		return get("uid");
	}

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return get("pid");
	}

	public M setLasttime(java.util.Date lasttime) {
		set("lasttime", lasttime);
		return (M)this;
	}

	public java.util.Date getLasttime() {
		return get("lasttime");
	}

	public M setExta(String exta) {
		set("exta", exta);
		return (M)this;
	}

	public String getExta() {
		return get("exta");
	}

	public M setIp(String ip) {
		set("ip", ip);
		return (M)this;
	}

	public String getIp() {
		return get("ip");
	}

}
