package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaperDetail<M extends BasePaperDetail<M>> extends Model<M> implements IBean {

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return get("pid");
	}

	public M setQid(Integer qid) {
		set("qid", qid);
		return (M)this;
	}

	public Integer getQid() {
		return get("qid");
	}

	public M setSid(Integer sid) {
		set("sid", sid);
		return (M)this;
	}

	public Integer getSid() {
		return get("sid");
	}

	public M setScore(Integer score) {
		set("score", score);
		return (M)this;
	}

	public Integer getScore() {
		return get("score");
	}

	public M setOrderid(Integer orderid) {
		set("orderid", orderid);
		return (M)this;
	}

	public Integer getOrderid() {
		return get("orderid");
	}

}
