package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaper<M extends BasePaper<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setPaperName(String paperName) {
		set("paper_name", paperName);
		return (M)this;
	}

	public String getPaperName() {
		return get("paper_name");
	}

	public M setAdminid(Integer adminid) {
		set("adminid", adminid);
		return (M)this;
	}

	public Integer getAdminid() {
		return get("adminid");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return get("status");
	}

	public M setStarttime(String starttime) {
		set("starttime", starttime);
		return (M)this;
	}

	public String getStarttime() {
		return get("starttime");
	}

	public M setEndtime(String endtime) {
		set("endtime", endtime);
		return (M)this;
	}

	public String getEndtime() {
		return get("endtime");
	}

	public M setPaperMinute(Integer paperMinute) {
		set("paper_minute", paperMinute);
		return (M)this;
	}

	public Integer getPaperMinute() {
		return get("paper_minute");
	}

	public M setTotalScore(Integer totalScore) {
		set("total_score", totalScore);
		return (M)this;
	}

	public Integer getTotalScore() {
		return get("total_score");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

	public M setQorder(String qorder) {
		set("qorder", qorder);
		return (M)this;
	}

	public String getQorder() {
		return get("qorder");
	}

	public M setPostdate(java.util.Date postdate) {
		set("postdate", postdate);
		return (M)this;
	}

	public java.util.Date getPostdate() {
		return get("postdate");
	}

	public M setShowScore(String showScore) {
		set("show_score", showScore);
		return (M)this;
	}

	public String getShowScore() {
		return get("show_score");
	}

	public M setIsranpaper(String isranpaper) {
		set("isranpaper", isranpaper);
		return (M)this;
	}

	public String getIsranpaper() {
		return get("isranpaper");
	}

	public M setDepartmentid(String departmentid) {
		set("departmentid", departmentid);
		return (M)this;
	}

	public String getDepartmentid() {
		return get("departmentid");
	}

}
