package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuestionDb<M extends BaseQuestionDb<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setDname(String dname) {
		set("dname", dname);
		return (M)this;
	}

	public String getDname() {
		return get("dname");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

	public M setAdminid(Integer adminid) {
		set("adminid", adminid);
		return (M)this;
	}

	public Integer getAdminid() {
		return get("adminid");
	}

	public M setCdate(java.util.Date cdate) {
		set("cdate", cdate);
		return (M)this;
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return get("status");
	}

	public M setDepartmentid(String departmentid) {
		set("departmentid", departmentid);
		return (M)this;
	}

	public String getDepartmentid() {
		return get("departmentid");
	}

	public M setCheckself(String checkself) {
		set("checkself", checkself);
		return (M)this;
	}

	public String getCheckself() {
		return get("checkself");
	}

}
