package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuestionCollection<M extends BaseQuestionCollection<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setQid(Integer qid) {
		set("qid", qid);
		return (M)this;
	}

	public Integer getQid() {
		return get("qid");
	}

	public M setUid(Integer uid) {
		set("uid", uid);
		return (M)this;
	}

	public Integer getUid() {
		return get("uid");
	}

	public M setCdate(java.util.Date cdate) {
		set("cdate", cdate);
		return (M)this;
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public M setDetailid(Integer detailid) {
		set("detailid", detailid);
		return (M)this;
	}

	public Integer getDetailid() {
		return get("detailid");
	}

}
