package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setLogtype(String logtype) {
		set("logtype", logtype);
		return (M)this;
	}

	public String getLogtype() {
		return get("logtype");
	}

	public M setUsertype(String usertype) {
		set("usertype", usertype);
		return (M)this;
	}

	public String getUsertype() {
		return get("usertype");
	}

	public M setUsername(String username) {
		set("username", username);
		return (M)this;
	}

	public String getUsername() {
		return get("username");
	}

	public M setUid(Integer uid) {
		set("uid", uid);
		return (M)this;
	}

	public Integer getUid() {
		return get("uid");
	}

	public M setLogtime(java.util.Date logtime) {
		set("logtime", logtime);
		return (M)this;
	}

	public java.util.Date getLogtime() {
		return get("logtime");
	}

	public M setIp(String ip) {
		set("ip", ip);
		return (M)this;
	}

	public String getIp() {
		return get("ip");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

}
