package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSystips<M extends BaseSystips<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setScode(String scode) {
		set("scode", scode);
		return (M)this;
	}

	public String getScode() {
		return get("scode");
	}

	public M setSdesc(String sdesc) {
		set("sdesc", sdesc);
		return (M)this;
	}

	public String getSdesc() {
		return get("sdesc");
	}

}
