package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminRolesSettings<M extends BaseAdminRolesSettings<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setPtype(Integer ptype) {
		set("ptype", ptype);
		return (M)this;
	}

	public Integer getPtype() {
		return get("ptype");
	}

	public M setPname(String pname) {
		set("pname", pname);
		return (M)this;
	}

	public String getPname() {
		return get("pname");
	}

	public M setPcode(String pcode) {
		set("pcode", pcode);
		return (M)this;
	}

	public String getPcode() {
		return get("pcode");
	}

	public M setPorder(Integer porder) {
		set("porder", porder);
		return (M)this;
	}

	public Integer getPorder() {
		return get("porder");
	}

}
