package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaperRandom<M extends BasePaperRandom<M>> extends Model<M> implements IBean {

	public M setRid(Integer rid) {
		set("rid", rid);
		return (M)this;
	}

	public Integer getRid() {
		return get("rid");
	}

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return get("pid");
	}

	public M setUid(Integer uid) {
		set("uid", uid);
		return (M)this;
	}

	public Integer getUid() {
		return get("uid");
	}

	public M setPaperdetail(String paperdetail) {
		set("paperdetail", paperdetail);
		return (M)this;
	}

	public String getPaperdetail() {
		return get("paperdetail");
	}

	public M setCdate(java.util.Date cdate) {
		set("cdate", cdate);
		return (M)this;
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

}
