package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaperSection<M extends BasePaperSection<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return get("pid");
	}

	public M setSectionName(String sectionName) {
		set("section_name", sectionName);
		return (M)this;
	}

	public String getSectionName() {
		return get("section_name");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

	public M setPerScore(Integer perScore) {
		set("per_score", perScore);
		return (M)this;
	}

	public Integer getPerScore() {
		return get("per_score");
	}

	public M setQuesnums(Integer quesnums) {
		set("quesnums", quesnums);
		return (M)this;
	}

	public Integer getQuesnums() {
		return get("quesnums");
	}

	public M setQueslevel(Integer queslevel) {
		set("queslevel", queslevel);
		return (M)this;
	}

	public Integer getQueslevel() {
		return get("queslevel");
	}

	public M setQuesdbid(Integer quesdbid) {
		set("quesdbid", quesdbid);
		return (M)this;
	}

	public Integer getQuesdbid() {
		return get("quesdbid");
	}

	public M setQuestype(Integer questype) {
		set("questype", questype);
		return (M)this;
	}

	public Integer getQuestype() {
		return get("questype");
	}

}
