package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminRoles<M extends BaseAdminRoles<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setRolename(String rolename) {
		set("rolename", rolename);
		return (M)this;
	}

	public String getRolename() {
		return get("rolename");
	}

	public M setRoleprivelege(String roleprivelege) {
		set("roleprivelege", roleprivelege);
		return (M)this;
	}

	public String getRoleprivelege() {
		return get("roleprivelege");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

	public M setCdate(java.util.Date cdate) {
		set("cdate", cdate);
		return (M)this;
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

}
