package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuestionOptions<M extends BaseQuestionOptions<M>> extends Model<M> implements IBean {

	public M setSalisa(String salisa) {
		set("salisa", salisa);
		return (M)this;
	}

	public String getSalisa() {
		return get("salisa");
	}

	public M setQid(Integer qid) {
		set("qid", qid);
		return (M)this;
	}

	public Integer getQid() {
		return get("qid");
	}

	public M setSoption(String soption) {
		set("soption", soption);
		return (M)this;
	}

	public String getSoption() {
		return get("soption");
	}

}
