package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExamInfo<M extends BaseExamInfo<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setUid(Integer uid) {
		set("uid", uid);
		return (M)this;
	}

	public Integer getUid() {
		return get("uid");
	}

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return get("pid");
	}

	public M setSdate(java.util.Date sdate) {
		set("sdate", sdate);
		return (M)this;
	}

	public java.util.Date getSdate() {
		return get("sdate");
	}

	public M setEdate(java.util.Date edate) {
		set("edate", edate);
		return (M)this;
	}

	public java.util.Date getEdate() {
		return get("edate");
	}

	public M setIp(String ip) {
		set("ip", ip);
		return (M)this;
	}

	public String getIp() {
		return get("ip");
	}

	public M setScore(Integer score) {
		set("score", score);
		return (M)this;
	}

	public Integer getScore() {
		return get("score");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return get("status");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

}
