package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuestion<M extends BaseQuestion<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setDbid(Integer dbid) {
		set("dbid", dbid);
		return (M)this;
	}

	public Integer getDbid() {
		return get("dbid");
	}

	public M setQtype(Integer qtype) {
		set("qtype", qtype);
		return (M)this;
	}

	public Integer getQtype() {
		return get("qtype");
	}

	public M setQlevel(Integer qlevel) {
		set("qlevel", qlevel);
		return (M)this;
	}

	public Integer getQlevel() {
		return get("qlevel");
	}

	public M setQfrom(Integer qfrom) {
		set("qfrom", qfrom);
		return (M)this;
	}

	public Integer getQfrom() {
		return get("qfrom");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return get("status");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}

	public String getContent() {
		return get("content");
	}

	public M setPostdate(java.util.Date postdate) {
		set("postdate", postdate);
		return (M)this;
	}

	public java.util.Date getPostdate() {
		return get("postdate");
	}

	public M setSkey(String skey) {
		set("skey", skey);
		return (M)this;
	}

	public String getSkey() {
		return get("skey");
	}

	public M setKeydesc(String keydesc) {
		set("keydesc", keydesc);
		return (M)this;
	}

	public String getKeydesc() {
		return get("keydesc");
	}

	public M setAdminid(Integer adminid) {
		set("adminid", adminid);
		return (M)this;
	}

	public Integer getAdminid() {
		return get("adminid");
	}

	public M setDepartmentid(String departmentid) {
		set("departmentid", departmentid);
		return (M)this;
	}

	public String getDepartmentid() {
		return get("departmentid");
	}

}
