package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExamDetail<M extends BaseExamDetail<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setUid(Integer uid) {
		set("uid", uid);
		return (M)this;
	}

	public Integer getUid() {
		return get("uid");
	}

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return get("pid");
	}

	public M setQid(Integer qid) {
		set("qid", qid);
		return (M)this;
	}

	public Integer getQid() {
		return get("qid");
	}

	public M setUserAnswer(String userAnswer) {
		set("user_answer", userAnswer);
		return (M)this;
	}

	public String getUserAnswer() {
		return get("user_answer");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return get("status");
	}

	public M setScore(Integer score) {
		set("score", score);
		return (M)this;
	}

	public Integer getScore() {
		return get("score");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

	public M setQtype(Integer qtype) {
		set("qtype", qtype);
		return (M)this;
	}

	public Integer getQtype() {
		return get("qtype");
	}

}
