package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePlus<M extends BasePlus<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setPname(String pname) {
		set("pname", pname);
		return (M)this;
	}

	public String getPname() {
		return get("pname");
	}

	public M setPdesc(String pdesc) {
		set("pdesc", pdesc);
		return (M)this;
	}

	public String getPdesc() {
		return get("pdesc");
	}

	public M setPhoto(String photo) {
		set("photo", photo);
		return (M)this;
	}

	public String getPhoto() {
		return get("photo");
	}

	public M setVurl(String vurl) {
		set("vurl", vurl);
		return (M)this;
	}

	public String getVurl() {
		return get("vurl");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return get("status");
	}

	public M setPurl(String purl) {
		set("purl", purl);
		return (M)this;
	}

	public String getPurl() {
		return get("purl");
	}

	public M setCdate(java.util.Date cdate) {
		set("cdate", cdate);
		return (M)this;
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

}
