package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return get("id");
	}

	public M setCname(String cname) {
		set("cname", cname);
		return (M)this;
	}

	public String getCname() {
		return get("cname");
	}

	public M setConfkey(String confkey) {
		set("confkey", confkey);
		return (M)this;
	}

	public String getConfkey() {
		return get("confkey");
	}

	public M setConfval(String confval) {
		set("confval", confval);
		return (M)this;
	}

	public String getConfval() {
		return get("confval");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return get("remark");
	}

}
