package com.coolshow.exam.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaperUsergroup<M extends BasePaperUsergroup<M>> extends Model<M> implements IBean {

	public M setPaperid(Integer paperid) {
		set("paperid", paperid);
		return (M)this;
	}

	public Integer getPaperid() {
		return get("paperid");
	}

	public M setUsergroupid(Integer usergroupid) {
		set("usergroupid", usergroupid);
		return (M)this;
	}

	public Integer getUsergroupid() {
		return get("usergroupid");
	}

}
